#
# Quarto configuration file
#
#
project:
  type: website
  render:
    - "*.qmd"
    - "*/*.qmd"
    - gallery/*/*.qmd

website:
  open-graph: true
  twitter-card: true
  site-url: https://orange.farmhill.in/
  navbar:
    logo: images/orange-logo.png   
    background: white
    right:
        - admissions/index.qmd
        - gallery/index.qmd
        - blog/index.qmd
        - contact/index.qmd
        - about/index.qmd
    tools:
      - icon: whatsapp
        href: "https://wa.me/918884000982?text=I%27m+interested+to+know+more+about+Orange."
      - icon: instagram
        href: "https://www.instagram.com/orangeschools"
      - icon: facebook
        href: https://facebook.com/Orangedaycare

  page-footer:
    border: true
    
    right:
      - icon: whatsapp
        href: "https://wa.me/8884000982?text=I%27m+interested+to+know+more+about+Orange."
      - icon: instagram
        href: "https://www.instagram.com/orangeschools"
      - icon: facebook
        href: https://facebook.com/Orangedaycare



format:
  html:
    page-layout: full
    theme:
      - cosmo
      - theme.scss
    css: styles.css

