#
# Quarto configuration file
#
#
project:
  type: website
  render:
    - "*.qmd"
    - "*/*.qmd"
    - gallery/*/*.qmd

website:
 
  description: "A place for children to learn, play and grow together."
  open-graph: true
  twitter-card: true
  site-url: https://orange.farmhill.in/
  navbar:
    logo: images/orange-logo.png   
    background: white
    right:
        - admissions/index.qmd
        - about/index.qmd
        - gallery/index.qmd
        - blog/index.qmd
        - contact/index.qmd
    tools:
      - icon: whatsapp
        href: "https://wa.me/918431032239?text=I%27m+interested+to+know+more+about+Farmhill."
      - icon: instagram
        href: "https://www.instagram.com/farmhill.learning"
      - icon: facebook
        href: https://facebook.com/farmhilllearning

  page-footer:
    border: true
    left: |
      _Farm Hill Learning Community_ is an initiative of [_Farm Hill Education Trust_](https://farmhill.in).<br>
      Other initiatives include [_Sambhavam Center for Autism_](https://sambhavam-autism.com/)
      and [_Subodha Learning Community_](https://subodha.farmhill.in).

    right:
      - icon: whatsapp
        href: "https://wa.me/918431032239?text=I%27m+interested+to+know+more+about+Farmhill."
      - icon: instagram
        href: "https://www.instagram.com/farmhill.learning"
      - icon: facebook
        href: https://facebook.com/farmhilllearning



format:
  html:
    page-layout: full
    theme:
      - cosmo
      - theme.scss
    css: styles.css

