---
title: "About"
---

Many of us would agree that the way we educate our children needs a serious overhaul. There needs to be many alternatives to the monocultural way we are currently educating them. There are a few alternative schools that have been running successfully but we need many more. Farm Hill intends to provide one such alternative.

The other thread running through Farm Hill is the need for us to work with people who are different from the most of us. When we say ‘every child is different’, many of us do not seem to be extending the definition of ‘different’ to include children whose neurologies are different. Farm Hill intends to address this by including children on the autism spectrum in our student population.

Over a period of time, we have found that the way one educates an autistic child is no different from the way one educates a neurotypical child; it is just that the current school system is suitable for neither. We intend to work with both neurotypical and autistic children in a setting that takes care of the unique needs of each child.

## The beginning 

The core team behind Farm Hill started their journey as parents of an autistic child, who was diagnosed in 2010. In their journey with Autism, they started and continue to run Sambhavam, an ABA based therapy center in Bangalore. Sambhavam works with about 30 to 40 families each year, providing early intervention, parent training and counselling, to help families living with autism manage their lives better.

We believe autism to be an expression of neurodiversity in humans. Different, not less - as Temple Grandin puts it. We don't think autism is a curse, tragedy, suffering or doom. We don't think people on the autism spectrum need to be 'cured' or be made 'normal' or that autism should be eradicated.

We believe that children and adults on the spectrum should be provided the help they need to make sense of themselves and the world around them. We also believe that the world around them (including their famlies) needs help to be more aware of autism and be able to make sense of people on the spectrum.

We see Farm Hill as a necessary continuation of our work at Sambhavam.

::: {.page-cta}

#### Want get involved?

Write to us!

<a href="/contact" class="btn btn-primary">Contact Us</a>

:::